<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>cdgfromyoutube</AssemblyName>
    <RootNamespace>CdgFromYoutube</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Lame" Version="2.1.0" />
  </ItemGroup>

</Project>
